AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Resources necessary for running the app

Parameters:
  Connection:
    Type: String

Resources:
  ClipFinderBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

  AppRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ['tasks.apprunner.amazonaws.com']
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: ClipFinderAppRunnerRole
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !GetAtt ClipFinderBucket.Arn
                - !Sub ${ClipFinderBucket.Arn}/*
            - Effect: Allow
              Action:
                - transcribe:CreateTranscriptionJob
                - transcribe:GetTranscriptionJob
                - transcribe:ListTranscriptionJobs
              Resource: '*'

  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: !Ref Connection
        AutoDeploymentsEnabled: true
        CodeRepository:
          CodeConfiguration:
            ConfigurationSource: REPOSITORY
          RepositoryUrl: https://github.com/allenheltondev/clip-finder
          SourceCodeVersion:
            Type: BRANCH
            Value: main
      InstanceConfiguration:
        InstanceRoleArn: !GetAtt AppRunnerRole.Arn

